### ISSUE TITLE
speed issue, some OLED types

### ISSUE THREAD

**Issue by OZ2CPU-thomas** [bitbank2/oled_turbo#3]
I have been using this quite a lot the last weeks, 
I found some displays dont like this type of high speed.
Solution : 
search for any CLOCK change in the first few functions, and add a nop like this
now all displays works

  I2CPORT = bOld & ~(1 << BB_SDA); // set data low
  nop;  // added a NOP on each side of any clock handeling in the code
  I2CPORT |= (1 << BB_SCL); // toggle clock
  nop;  // added a NOP on each side of any clock handeling in the code
  I2C_CLK_LOW();

**Comment by hasaranga** [comment]
**_NOP();**
Thank you very much!

**Comment by bitbank2** [comment]
I'm glad you find the code useful. Another possible cause of the difference in tolerated clock speeds is the pullup resistors. A clean pulse is needed and the faster you go, the worse the signal gets. The SSD1306 should react identically in all configurations unless the external pullups and line capacitance is different.
