### ISSUE TITLE
Compiling for attiny85

### ISSUE THREAD

**Issue by bctstkla** [bitbank2/oled_turbo#5]
Hi,

tried unsuccessfully compiling the sample code for attiny85.
I2CDDR and PORTD are undefined, and the global variables use over 200% of the 85's memory.

Since you've already run it on the 85, there must be something I'm missing?

**Comment by bitbank2** [comment]
Over time I worked my way out of the ATtiny85 and towards the ATmega328, so it makes sense that it doesn't work any more :(
Sorry, but I'm working only on "big memory" MCUs lately.

**Comment by bctstkla** [comment]
Hi @bitbank2, thanks for your reply. Unfortunately even the oldest commit from May 2018 has the same issue with defines. 
Would you by chance have the -85 version left somewhere, from the time of blog post https://bitbanksoftware.blogspot.com/2018/05/fast-ssd1306-oled-drawing-with-i2c-bit.html ?

**Comment by bitbank2** [comment]
If you look at the history of the code and it still doesn't build for ATtiny85, that sounds like your build environment is the problem. I used the DigiSpark board with their bootloader.

**Comment by bctstkla** [comment]
Hi, thanks, but I think that's unlikely, since the first commit in this repository already has the defines
#define I2CPORT PORTD
#define I2CDDR DDRD

Neither of which compile for attiny (tried several boards, with and without bootloader - I usually don't use one).

If I've understood correctly, attiny85 only has PORTB, which would support the hypothesis that the code - even in the first commit in the repo - is already non-attiny-compatible.
